name: navigation
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter  

  menu:
    path: ../features/menu
  detailed_dish:
    path: ../features/detailed_dish
  home:
    path: ../features/home
  settings:
    path: ../features/settings
  order_history:
    path: ../features/order_history
  shopping_cart:
    path: ../features/shopping_cart
  authentication:
    path: ../features/authentication
  main:
    path: ../features/main
  core:
    path: ../core
  auto_route: ^5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  auto_route_generator: 5.0.2
  
flutter:
